// This file is generated by rust-protobuf 2.10.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `output.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_10_1;

#[derive(PartialEq,Clone,Default)]
pub struct request {
    // message fields
    pub keepalive: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a request {
    fn default() -> &'a request {
        <request as ::protobuf::Message>::default_instance()
    }
}

impl request {
    pub fn new() -> request {
        ::std::default::Default::default()
    }

    // bool keepalive = 1;


    pub fn get_keepalive(&self) -> bool {
        self.keepalive
    }
    pub fn clear_keepalive(&mut self) {
        self.keepalive = false;
    }

    // Param is passed by value, moved
    pub fn set_keepalive(&mut self, v: bool) {
        self.keepalive = v;
    }
}

impl ::protobuf::Message for request {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.keepalive = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.keepalive != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.keepalive != false {
            os.write_bool(1, self.keepalive)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> request {
        request::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "keepalive",
                    |m: &request| { &m.keepalive },
                    |m: &mut request| { &mut m.keepalive },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<request>(
                    "request",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static request {
        static mut instance: ::protobuf::lazy::Lazy<request> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const request,
        };
        unsafe {
            instance.get(request::new)
        }
    }
}

impl ::protobuf::Clear for request {
    fn clear(&mut self) {
        self.keepalive = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for request {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct response {
    // message fields
    pub time: ::protobuf::SingularPtrField<::protobuf::well_known_types::Timestamp>,
    pub priority: super::schema::priority,
    pub source: super::schema::source,
    pub rule: ::std::string::String,
    pub output: ::std::string::String,
    pub output_fields: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    pub hostname: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a response {
    fn default() -> &'a response {
        <response as ::protobuf::Message>::default_instance()
    }
}

impl response {
    pub fn new() -> response {
        ::std::default::Default::default()
    }

    // .google.protobuf.Timestamp time = 1;


    pub fn get_time(&self) -> &::protobuf::well_known_types::Timestamp {
        self.time.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::default_instance())
    }
    pub fn clear_time(&mut self) {
        self.time.clear();
    }

    pub fn has_time(&self) -> bool {
        self.time.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time(&mut self, v: ::protobuf::well_known_types::Timestamp) {
        self.time = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_time(&mut self) -> &mut ::protobuf::well_known_types::Timestamp {
        if self.time.is_none() {
            self.time.set_default();
        }
        self.time.as_mut().unwrap()
    }

    // Take field
    pub fn take_time(&mut self) -> ::protobuf::well_known_types::Timestamp {
        self.time.take().unwrap_or_else(|| ::protobuf::well_known_types::Timestamp::new())
    }

    // .falco.schema.priority priority = 2;


    pub fn get_priority(&self) -> super::schema::priority {
        self.priority
    }
    pub fn clear_priority(&mut self) {
        self.priority = super::schema::priority::EMERGENCY;
    }

    // Param is passed by value, moved
    pub fn set_priority(&mut self, v: super::schema::priority) {
        self.priority = v;
    }

    // .falco.schema.source source = 3;


    pub fn get_source(&self) -> super::schema::source {
        self.source
    }
    pub fn clear_source(&mut self) {
        self.source = super::schema::source::SYSCALL;
    }

    // Param is passed by value, moved
    pub fn set_source(&mut self, v: super::schema::source) {
        self.source = v;
    }

    // string rule = 4;


    pub fn get_rule(&self) -> &str {
        &self.rule
    }
    pub fn clear_rule(&mut self) {
        self.rule.clear();
    }

    // Param is passed by value, moved
    pub fn set_rule(&mut self, v: ::std::string::String) {
        self.rule = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rule(&mut self) -> &mut ::std::string::String {
        &mut self.rule
    }

    // Take field
    pub fn take_rule(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rule, ::std::string::String::new())
    }

    // string output = 5;


    pub fn get_output(&self) -> &str {
        &self.output
    }
    pub fn clear_output(&mut self) {
        self.output.clear();
    }

    // Param is passed by value, moved
    pub fn set_output(&mut self, v: ::std::string::String) {
        self.output = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_output(&mut self) -> &mut ::std::string::String {
        &mut self.output
    }

    // Take field
    pub fn take_output(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.output, ::std::string::String::new())
    }

    // repeated .falco.output.response.OutputFieldsEntry output_fields = 6;


    pub fn get_output_fields(&self) -> &::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &self.output_fields
    }
    pub fn clear_output_fields(&mut self) {
        self.output_fields.clear();
    }

    // Param is passed by value, moved
    pub fn set_output_fields(&mut self, v: ::std::collections::HashMap<::std::string::String, ::std::string::String>) {
        self.output_fields = v;
    }

    // Mutable pointer to the field.
    pub fn mut_output_fields(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &mut self.output_fields
    }

    // Take field
    pub fn take_output_fields(&mut self) -> ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        ::std::mem::replace(&mut self.output_fields, ::std::collections::HashMap::new())
    }

    // string hostname = 7;


    pub fn get_hostname(&self) -> &str {
        &self.hostname
    }
    pub fn clear_hostname(&mut self) {
        self.hostname.clear();
    }

    // Param is passed by value, moved
    pub fn set_hostname(&mut self, v: ::std::string::String) {
        self.hostname = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_hostname(&mut self) -> &mut ::std::string::String {
        &mut self.hostname
    }

    // Take field
    pub fn take_hostname(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.hostname, ::std::string::String::new())
    }
}

impl ::protobuf::Message for response {
    fn is_initialized(&self) -> bool {
        for v in &self.time {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.time)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.priority, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.source, 3, &mut self.unknown_fields)?
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rule)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.output)?;
                },
                6 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(wire_type, is, &mut self.output_fields)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.hostname)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.priority != super::schema::priority::EMERGENCY {
            my_size += ::protobuf::rt::enum_size(2, self.priority);
        }
        if self.source != super::schema::source::SYSCALL {
            my_size += ::protobuf::rt::enum_size(3, self.source);
        }
        if !self.rule.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.rule);
        }
        if !self.output.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.output);
        }
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(6, &self.output_fields);
        if !self.hostname.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.hostname);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.time.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.priority != super::schema::priority::EMERGENCY {
            os.write_enum(2, self.priority.value())?;
        }
        if self.source != super::schema::source::SYSCALL {
            os.write_enum(3, self.source.value())?;
        }
        if !self.rule.is_empty() {
            os.write_string(4, &self.rule)?;
        }
        if !self.output.is_empty() {
            os.write_string(5, &self.output)?;
        }
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(6, &self.output_fields, os)?;
        if !self.hostname.is_empty() {
            os.write_string(7, &self.hostname)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> response {
        response::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Timestamp>>(
                    "time",
                    |m: &response| { &m.time },
                    |m: &mut response| { &mut m.time },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::schema::priority>>(
                    "priority",
                    |m: &response| { &m.priority },
                    |m: &mut response| { &mut m.priority },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::schema::source>>(
                    "source",
                    |m: &response| { &m.source },
                    |m: &mut response| { &mut m.source },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rule",
                    |m: &response| { &m.rule },
                    |m: &mut response| { &mut m.rule },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "output",
                    |m: &response| { &m.output },
                    |m: &mut response| { &mut m.output },
                ));
                fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(
                    "output_fields",
                    |m: &response| { &m.output_fields },
                    |m: &mut response| { &mut m.output_fields },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "hostname",
                    |m: &response| { &m.hostname },
                    |m: &mut response| { &mut m.hostname },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<response>(
                    "response",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static response {
        static mut instance: ::protobuf::lazy::Lazy<response> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const response,
        };
        unsafe {
            instance.get(response::new)
        }
    }
}

impl ::protobuf::Clear for response {
    fn clear(&mut self) {
        self.time.clear();
        self.priority = super::schema::priority::EMERGENCY;
        self.source = super::schema::source::SYSCALL;
        self.rule.clear();
        self.output.clear();
        self.output_fields.clear();
        self.hostname.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for response {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for response {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0coutput.proto\x12\x0cfalco.output\x1a\x1fgoogle/protobuf/timestamp.\
    proto\x1a\x0cschema.proto\"'\n\x07request\x12\x1c\n\tkeepalive\x18\x01\
    \x20\x01(\x08R\tkeepalive\"\xf4\x02\n\x08response\x12.\n\x04time\x18\x01\
    \x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x04time\x122\n\x08priority\
    \x18\x02\x20\x01(\x0e2\x16.falco.schema.priorityR\x08priority\x12,\n\x06\
    source\x18\x03\x20\x01(\x0e2\x14.falco.schema.sourceR\x06source\x12\x12\
    \n\x04rule\x18\x04\x20\x01(\tR\x04rule\x12\x16\n\x06output\x18\x05\x20\
    \x01(\tR\x06output\x12M\n\routput_fields\x18\x06\x20\x03(\x0b2(.falco.ou\
    tput.response.OutputFieldsEntryR\x0coutputFields\x12\x1a\n\x08hostname\
    \x18\x07\x20\x01(\tR\x08hostname\x1a?\n\x11OutputFieldsEntry\x12\x10\n\
    \x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\x02\x20\x01(\t\
    R\x05value:\x028\x012G\n\x07service\x12<\n\tsubscribe\x12\x15.falco.outp\
    ut.request\x1a\x16.falco.output.response0\x01J\xd5\r\n\x06\x12\x04\0\0&\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\x02\x03\0\x12\x03\x02\0)\n\t\
    \n\x02\x03\x01\x12\x03\x03\0\x16\n\x08\n\x01\x02\x12\x03\x05\0\x15\n\x8a\
    \x01\n\x02\x06\0\x12\x04\n\0\x0c\x01\x1a~\x20The\x20`subscribe`\x20servi\
    ce\x20defines\x20the\x20RPC\x20call\n\x20to\x20perform\x20an\x20output\
    \x20`request`\x20which\x20will\x20lead\x20to\x20obtain\x20an\x20output\
    \x20`response`.\n\n\n\n\x03\x06\0\x01\x12\x03\n\x08\x0f\n\x0b\n\x04\x06\
    \0\x02\0\x12\x03\x0b\x023\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x0b\x06\
    \x0f\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\x0b\x10\x17\n\x0c\n\x05\x06\0\
    \x02\0\x06\x12\x03\x0b\"(\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x0b)1\n\
    \x89\x03\n\x02\x04\0\x12\x04\x14\0\x18\x01\x1a\xfc\x02\x20The\x20`reques\
    t`\x20message\x20is\x20the\x20logical\x20representation\x20of\x20the\x20\
    request\x20model.\n\x20It\x20is\x20the\x20input\x20of\x20the\x20`subscri\
    be`\x20service.\n\x20It\x20is\x20used\x20to\x20configure\x20the\x20kind\
    \x20of\x20subscription\x20to\x20the\x20gRPC\x20streaming\x20server.\n\n\
    \x20By\x20default\x20the\x20request\x20asks\x20to\x20the\x20server\x20to\
    \x20only\x20receive\x20the\x20accumulated\x20events.\n\x20In\x20case\x20\
    you\x20want\x20to\x20wait\x20indefinitely\x20for\x20new\x20events\x20to\
    \x20come\x20set\x20the\x20keepalive\x20option\x20to\x20true.\n\n\n\n\x03\
    \x04\0\x01\x12\x03\x14\x08\x0f\n\xc9\x01\n\x04\x04\0\x02\0\x12\x03\x15\
    \x02\x15\"\xbb\x01\x20string\x20duration\x20=\x202;\x20//\x20TODO(leodid\
    o,\x20fntlnz):\x20not\x20handled\x20yet\x20but\x20keeping\x20for\x20refe\
    rence.\n\x20repeated\x20string\x20tags\x20=\x203;\x20//\x20TODO(leodido,\
    \x20fntlnz):\x20not\x20handled\x20yet\x20but\x20keeping\x20for\x20refere\
    nce.\n\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x15\x02\x14\x11\n\x0c\n\x05\x04\
    \0\x02\0\x05\x12\x03\x15\x02\x06\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x15\
    \x07\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x15\x13\x14\n\xcb\x01\n\x02\
    \x04\x01\x12\x04\x1d\0&\x01\x1a\xbe\x01\x20The\x20`response`\x20message\
    \x20is\x20the\x20logical\x20representation\x20of\x20the\x20output\x20mod\
    el.\n\x20It\x20contains\x20all\x20the\x20elements\x20that\x20Falco\x20em\
    its\x20in\x20an\x20output\x20along\x20with\x20the\n\x20definitions\x20fo\
    r\x20priorities\x20and\x20source.\n\n\n\n\x03\x04\x01\x01\x12\x03\x1d\
    \x08\x10\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x1e\x02%\n\r\n\x05\x04\x01\
    \x02\0\x04\x12\x04\x1e\x02\x1d\x12\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\
    \x1e\x02\x1b\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1e\x1c\x20\n\x0c\n\
    \x05\x04\x01\x02\0\x03\x12\x03\x1e#$\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\
    \x1f\x02%\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04\x1f\x02\x1e%\n\x0c\n\x05\
    \x04\x01\x02\x01\x06\x12\x03\x1f\x02\x17\n\x0c\n\x05\x04\x01\x02\x01\x01\
    \x12\x03\x1f\x18\x20\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x1f#$\n\x0b\
    \n\x04\x04\x01\x02\x02\x12\x03\x20\x02!\n\r\n\x05\x04\x01\x02\x02\x04\
    \x12\x04\x20\x02\x1f%\n\x0c\n\x05\x04\x01\x02\x02\x06\x12\x03\x20\x02\
    \x15\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x20\x16\x1c\n\x0c\n\x05\x04\
    \x01\x02\x02\x03\x12\x03\x20\x1f\x20\n\x0b\n\x04\x04\x01\x02\x03\x12\x03\
    !\x02\x12\n\r\n\x05\x04\x01\x02\x03\x04\x12\x04!\x02\x20!\n\x0c\n\x05\
    \x04\x01\x02\x03\x05\x12\x03!\x02\x08\n\x0c\n\x05\x04\x01\x02\x03\x01\
    \x12\x03!\t\r\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03!\x10\x11\n\x0b\n\
    \x04\x04\x01\x02\x04\x12\x03\"\x02\x14\n\r\n\x05\x04\x01\x02\x04\x04\x12\
    \x04\"\x02!\x12\n\x0c\n\x05\x04\x01\x02\x04\x05\x12\x03\"\x02\x08\n\x0c\
    \n\x05\x04\x01\x02\x04\x01\x12\x03\"\t\x0f\n\x0c\n\x05\x04\x01\x02\x04\
    \x03\x12\x03\"\x12\x13\n\x0b\n\x04\x04\x01\x02\x05\x12\x03#\x02(\n\r\n\
    \x05\x04\x01\x02\x05\x04\x12\x04#\x02\"\x14\n\x0c\n\x05\x04\x01\x02\x05\
    \x06\x12\x03#\x02\x15\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x03#\x16#\n\
    \x0c\n\x05\x04\x01\x02\x05\x03\x12\x03#&'\no\n\x04\x04\x01\x02\x06\x12\
    \x03$\x02\x16\"b\x20repeated\x20string\x20tags\x20=\x208;\x20//\x20TODO(\
    leodido,fntlnz):\x20tags\x20not\x20supported\x20yet,\x20keeping\x20for\
    \x20reference\n\n\r\n\x05\x04\x01\x02\x06\x04\x12\x04$\x02#(\n\x0c\n\x05\
    \x04\x01\x02\x06\x05\x12\x03$\x02\x08\n\x0c\n\x05\x04\x01\x02\x06\x01\
    \x12\x03$\t\x11\n\x0c\n\x05\x04\x01\x02\x06\x03\x12\x03$\x14\x15b\x06pro\
    to3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
